/*
Copyright 2026 Flant JSC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package status

import (
	"strings"
	"testing"
)

func TestCLIBanner(t *testing.T) {
	output := cliBanner("v9.9.9-test")

	for _, want := range []string{"Generated by Deckhouse CLI", "v9.9.9-test"} {
		if !strings.Contains(output, want) {
			t.Errorf("cliBanner output missing %q:\n%s", want, output)
		}
	}
}
