//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2026 Flant JSC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies the receiver into out.
func (in *LocalSnapshotRef) DeepCopyInto(out *LocalSnapshotRef) {
	*out = *in
}

// DeepCopy creates a new LocalSnapshotRef.
func (in *LocalSnapshotRef) DeepCopy() *LocalSnapshotRef {
	if in == nil {
		return nil
	}
	out := new(LocalSnapshotRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *SnapshotExport) DeepCopyInto(out *SnapshotExport) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a new SnapshotExport.
func (in *SnapshotExport) DeepCopy() *SnapshotExport {
	if in == nil {
		return nil
	}
	out := new(SnapshotExport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject creates a new runtime.Object.
func (in *SnapshotExport) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies the receiver into out.
func (in *SnapshotExportList) DeepCopyInto(out *SnapshotExportList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SnapshotExport, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a new SnapshotExportList.
func (in *SnapshotExportList) DeepCopy() *SnapshotExportList {
	if in == nil {
		return nil
	}
	out := new(SnapshotExportList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject creates a new runtime.Object.
func (in *SnapshotExportList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies the receiver into out.
func (in *SnapshotExportSpec) DeepCopyInto(out *SnapshotExportSpec) {
	*out = *in
	out.SnapshotRef = in.SnapshotRef
}

// DeepCopy creates a new SnapshotExportSpec.
func (in *SnapshotExportSpec) DeepCopy() *SnapshotExportSpec {
	if in == nil {
		return nil
	}
	out := new(SnapshotExportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *SnapshotExportStatus) DeepCopyInto(out *SnapshotExportStatus) {
	*out = *in
	if in.DataSnapshots != nil {
		in, out := &in.DataSnapshots, &out.DataSnapshots
		*out = make([]SnapshotExportDataEntry, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a new SnapshotExportStatus.
func (in *SnapshotExportStatus) DeepCopy() *SnapshotExportStatus {
	if in == nil {
		return nil
	}
	out := new(SnapshotExportStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *SnapshotExportDataEntry) DeepCopyInto(out *SnapshotExportDataEntry) {
	*out = *in
}

// DeepCopy creates a new SnapshotExportDataEntry.
func (in *SnapshotExportDataEntry) DeepCopy() *SnapshotExportDataEntry {
	if in == nil {
		return nil
	}
	out := new(SnapshotExportDataEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *SnapshotImport) DeepCopyInto(out *SnapshotImport) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a new SnapshotImport.
func (in *SnapshotImport) DeepCopy() *SnapshotImport {
	if in == nil {
		return nil
	}
	out := new(SnapshotImport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject creates a new runtime.Object.
func (in *SnapshotImport) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies the receiver into out.
func (in *SnapshotImportList) DeepCopyInto(out *SnapshotImportList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SnapshotImport, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a new SnapshotImportList.
func (in *SnapshotImportList) DeepCopy() *SnapshotImportList {
	if in == nil {
		return nil
	}
	out := new(SnapshotImportList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject creates a new runtime.Object.
func (in *SnapshotImportList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies the receiver into out.
func (in *SnapshotImportSpec) DeepCopyInto(out *SnapshotImportSpec) {
	*out = *in
	if in.StorageClassMapping != nil {
		in, out := &in.StorageClassMapping, &out.StorageClassMapping
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy creates a new SnapshotImportSpec.
func (in *SnapshotImportSpec) DeepCopy() *SnapshotImportSpec {
	if in == nil {
		return nil
	}
	out := new(SnapshotImportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *SnapshotImportStatus) DeepCopyInto(out *SnapshotImportStatus) {
	*out = *in
	if in.DataSnapshots != nil {
		in, out := &in.DataSnapshots, &out.DataSnapshots
		*out = make([]SnapshotImportDataEntry, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a new SnapshotImportStatus.
func (in *SnapshotImportStatus) DeepCopy() *SnapshotImportStatus {
	if in == nil {
		return nil
	}
	out := new(SnapshotImportStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *SnapshotImportDataEntry) DeepCopyInto(out *SnapshotImportDataEntry) {
	*out = *in
}

// DeepCopy creates a new SnapshotImportDataEntry.
func (in *SnapshotImportDataEntry) DeepCopy() *SnapshotImportDataEntry {
	if in == nil {
		return nil
	}
	out := new(SnapshotImportDataEntry)
	in.DeepCopyInto(out)
	return out
}
