---
apiVersion: v1
kind: Secret
metadata:
  name: registrysecret
  namespace: test
  {{- include "helm_lib_module_labels" (list . (dict "app" "server")) | nindent 2 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Module.Package.Registry.dockercfg }}
