apiVersion: v1
kind: Service
metadata:
  name: {{ .Application.Instance.Name }}-server
spec:
  type: ClusterIP
  selector:
    app: {{ .Application.Instance.Name }}-server
  ports:
    - port: 5678
      targetPort: http
      protocol: TCP
      name: http
