{{- if .Capabilities.APIVersions.Has "autoscaling.k8s.io/v1/VerticalPodAutoscaler" }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ .Application.Instance.Name }}-server
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Application.Instance.Name }}-server
  updatePolicy:
    updateMode: Initial
  resourcePolicy:
    containerPolicies:
      - containerName: server
        minAllowed:
          cpu: "10m"
          memory: "32Mi"
        maxAllowed:
          cpu: "500m"
          memory: "512Mi"
{{- end }}
