name: trdl-release
on:
  create:

env:
  PRIVATE_REPO_TOKEN: ${{ secrets.FOX_PRIVATE_TOKEN }}

permissions:
  contents: write  

jobs:
  release:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    name: Perform deckhouse-cli release using trdl server
    runs-on: [self-hosted, regular]
    container:
      image: ubuntu:22.04    
    steps:
    - name: Release
      env:
        PRIVATE_REPO_TOKEN: ${{ secrets.FOX_PRIVATE_TOKEN }}
      uses: werf/trdl-vault-actions/release@main
      with:
        git-tag: ${{ github.event.ref }}
        vault-addr: ${{ secrets.TRDL_VAULT_ADDR }}
        project-name: deckhouse-cli
        vault-auth-method: approle
        vault-role-id: ${{ secrets.TRDL_VAULT_ROLE_ID }}
        vault-secret-id: ${{ secrets.TRDL_VAULT_SECRET_ID }}
