name: trdl-release
on:
  create:

jobs:
  release:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    name: Perform deckhouse-cli release using trdl server
    runs-on: ubuntu-latest
    steps:
    - name: Release
      uses: werf/trdl-vault-actions/release@main
      with:
        vault-addr: https://trrr.flant.dev
        project-name: deckhouse-cli
        git-tag: ${{ github.event.ref }}
        vault-auth-method: approle
        vault-role-id: f1b89aca-a28b-04ed-1631-6413758a4ee3 
        vault-secret-id: 77593065-7cea-9ad8-eae6-f5e61a8197ca
