name: trdl-publish
on:
  push:
    paths:
      - trdl_channels.yaml

defaults:
  run:
    shell: bash

jobs:
  publish:
    name: Publish release channels using trdl server
    runs-on: ubuntu-22.04
    steps:
      - name: Publish
        uses: werf/trdl-vault-actions/publish@main
        with:
          vault-addr: https://trrr.flant.dev
          project-name: deckhouse-cli
          vault-auth-method: approle
          vault-role-id: f1b89aca-a28b-04ed-1631-6413758a4ee3
          vault-secret-id: dddec62a-39a9-71e2-fea4-f631cf399b09
