name: trdl-release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
  workflow_dispatch:        

permissions:
  contents: write  

env:
  GOPRIVATE: "flant.internal"
  PRIVATE_REPO: "${{secrets.DECKHOUSE_PRIVATE_REPO}}"


jobs:
  release:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    name: Perform deckhouse-cli release using trdl server
    runs-on: [self-hosted, regular]    
    steps:

    - name: Release
      uses: werf/trdl-vault-actions/release@main
      with:
        git-tag: ${{ github.ref_name }}
        vault-addr: ${{ secrets.TRDL_VAULT_ADDR }}
        project-name: deckhouse-cli
        vault-auth-method: approle
        vault-role-id: ${{ secrets.TRDL_VAULT_ROLE_ID }}
        vault-secret-id: ${{ secrets.TRDL_VAULT_SECRET_ID }}
